# -*- coding: utf-8 -*-
"""Modul_Penjumlahan.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16xAsWW0OuQMHSweSMmsthKZ7SFN-SHbd
"""

def penjumlahan(angka_1,angka_2):
  jumlah = angka_1 + angka_1
  return jumlah